sudo: required
services:
  - docker
script:
  - docker build -t adamperyman/mongo:$TRAVIS_BRANCH
before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
  - provider: script
    script: docker push adamperyman/mongo:$TRAVIS_BRANCH
    on:
      branch: "*"
